name: Suggestion
description: Suggestion
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your suggestion related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: Ex. I'm always frustrated when [...]
  - type: textarea
    id: mod
    attributes:
      label: Mod suggestion
      description: Link to mod and describe why you would like to see the mod in the pack?
      placeholder: >
        Link to mod:

        A clear and concise description of what the mod what add and why you would like it in the pack.
